### ISSUE TITLE
Use less CPU time if idle

### ISSUE THREAD

**Issue by klausdorer** [Gama11/RoboViz#53]
RoboViz is using 10% of my CPU when it is idle (not connected to a server). I wonder why. I would expect that it is trying to connect once a second or so, but does not do other things in the meantime.
Ubuntu 12.04

**Comment by klausdorer** [comment]
Sorry, duplicate of issue #17

**Comment by Gama11** [comment]
You can close issues you created yourself (next to the comment button), even if you don't have push access.
