### ISSUE TITLE
Live mode: add option to display deviation of server time from real time

### ISSUE THREAD

**Issue by Gama11** [Gama11/RoboViz#9]
RoboViz would have to cache the time values of the last 5 or so seconds along with the real time and calculate at what percentage of real time the server is currently running.

This could be displayed as a factor in a textfield next to the game status. The visibility of that text could be toggled via a shortcut (`M` perhaps).

**Comment by pmacalpine** [comment]
This feature is made a bit more complicated by the fact that messages sent to the monitor, unlike agents, do not contain a server time stamp.  By default messages are sent to the server every 0.04 seconds ($renderStep variable in ~/.simspark/spark.rb).  I would probably use this default value as the expected real time speed of messages arriving when a game is not running, but if a game is running (seeing differences in game times between messages) then use that the game time delta between messages.  By using differences in reported game time (when available) this metric will be somewhat resilient to network issues potentially causing messages for the monitor to be dropped.  Using game time differences will also show an appropriate speed up value when not running in real time mode.

**Comment by pmacalpine** [comment]
I'm working on this and should have an implementation soon.
